### PR TITLE
Allow plugins to add their own Element Types

### PR DESCRIPTION
**Pull request by joshangell**
Hey!

First of all - great plugin and thanks for all the hard work :)

I have added a couple of hooks to allow plugins to add their own Element Types to the field type. This addresses issue #37 that I raised recently.

I have tested it with my own plugins and added multiple Element Types from one plugin but have not tested multiple plugins.

### CODE REVIEW

**Comment by samhibberd** [comment]
Great work @joshangell, been on the list for a while now so thanks for pushing it out!

Sam

**Comment by joshangell** [comment]
Awesome! Glad you like it. Just a heads up - the changelog on the README isn’t showing that update :)

**Comment by samhibberd** [comment]
Odd, it is for me.

**Comment by joshangell** [comment]
What [here](https://github.com/fruitstudios/LinkIt#fruitlinkit-changelog)?

**Comment by samhibberd** [comment]
Sorry, misread, updating!

**Comment by joshangell** [comment]
Np!

Josh

**Pull request merged**
